### PR TITLE
About Us Page Added

### PR DESCRIPTION
**Pull request by Rishi22-Coding**
#23 Issue Solved

### CODE REVIEW

**Comment by a-rokay** [comment]
The title should be set to something more fitting.

**Comment by Rishi22-Coding** [comment]
@a-rokay okay let me change it

**Comment by Rishi22-Coding** [comment]
@a-rokay is it okay I updated the title.

**Comment by a-rokay** [comment]
Looks good

**Comment by Rishi22-Coding** [comment]
@a-rokay thanks can you please merge and close the issue.

**Comment by a-rokay** [comment]
I don't have access

**Comment by qw-erty** [comment]
great

**Pull request merged**
